accepted = [
    "Apache-2.0",
    "MIT",
    "Zlib",
    "MPL-2.0",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "MIT-0",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
